CREATE TABLE USER_ACCOUNT (
    USER_ID NUMBER PRIMARY KEY
);

CREATE TABLE WATER_INFO (
    WATER_INFO_ID NUMBER PRIMARY KEY,
    PROPERTIES VARCHAR(255),
    RECOMMENDATIONS VARCHAR(255),
    USER_ID NUMBER
);

CREATE TABLE WATER_CONSUMPTION (
    CONSUMPTION_ID NUMBER PRIMARY KEY,
    VOLUME NUMBER,
    USER_ID NUMBER
);

CREATE TABLE SUPPORT_TOOL (
    TOOL_ID NUMBER PRIMARY KEY,
    TOOL_NAME VARCHAR(100),
    TOOL_TYPE VARCHAR(50)
);

CREATE TABLE RELAXATION_TOOL (
    TOOL_ID NUMBER PRIMARY KEY
);

CREATE TABLE EMOTIONAL_SUPPORT (
    TOOL_ID NUMBER PRIMARY KEY
);

CREATE TABLE PROCESS_RESULT (
    RESULT_ID NUMBER PRIMARY KEY,
    RESULT_TYPE VARCHAR(50),
    CONTENT VARCHAR(255),
    TOOL_ID NUMBER
);
