-- =========================
-- USER_ACCOUNT
-- =========================
CREATE TABLE USER_ACCOUNT (
    USER_ID NUMBER PRIMARY KEY
);

-- =========================
-- WATER_INFO
-- =========================
CREATE TABLE WATER_INFO (
    WATER_INFO_ID NUMBER PRIMARY KEY,
    PROPERTIES VARCHAR(255) NOT NULL,
    RECOMMENDATIONS VARCHAR(255) NOT NULL,
    USER_ID NUMBER NOT NULL,

    CONSTRAINT FK_WATER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USER_ACCOUNT (USER_ID),

    CONSTRAINT CHK_PROPERTIES_FORMAT
        CHECK (
            PROPERTIES ~ '^[A-Za-zА-Яа-я0-9 ,.-]+$'
        ),

    CONSTRAINT CHK_RECOMMENDATIONS_FORMAT
        CHECK (
            RECOMMENDATIONS ~ '^[A-Za-zА-Яа-я0-9 ,.-]+$'
        )
);

-- =========================
-- WATER_CONSUMPTION
-- =========================
CREATE TABLE WATER_CONSUMPTION (
    CONSUMPTION_ID NUMBER PRIMARY KEY,
    VOLUME NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,

    CONSTRAINT FK_CONSUMPTION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USER_ACCOUNT (USER_ID),

    CONSTRAINT CHK_VOLUME_POSITIVE
        CHECK (
            VOLUME > 0
        )
);

-- =========================
-- SUPPORT_TOOL
-- =========================
CREATE TABLE SUPPORT_TOOL (
    TOOL_ID NUMBER PRIMARY KEY,
    TOOL_NAME VARCHAR(100) NOT NULL,
    TOOL_CATEGORY VARCHAR(30) NOT NULL,

    CONSTRAINT CHK_TOOL_NAME
        CHECK (
            TOOL_NAME ~ '^[A-Za-zА-Яа-я0-9 ]+$'
        )
);

-- =========================
-- RELAXATION_TOOL
-- =========================
CREATE TABLE RELAXATION_TOOL (
    TOOL_ID NUMBER PRIMARY KEY,

    CONSTRAINT FK_RELAX_TOOL
        FOREIGN KEY (TOOL_ID)
        REFERENCES SUPPORT_TOOL (TOOL_ID)
);

-- =========================
-- EMOTIONAL_SUPPORT
-- =========================
CREATE TABLE EMOTIONAL_SUPPORT (
    TOOL_ID NUMBER PRIMARY KEY,

    CONSTRAINT FK_EMOTIONAL_TOOL
        FOREIGN KEY (TOOL_ID)
        REFERENCES SUPPORT_TOOL (TOOL_ID)
);

-- =========================
-- RESULT
-- =========================
CREATE TABLE RESULT (
    RESULT_ID NUMBER PRIMARY KEY,
    RESULT_TYPE VARCHAR(50) NOT NULL,
    CONTENT_TEXT VARCHAR(255) NOT NULL,
    TOOL_ID NUMBER NOT NULL,

    CONSTRAINT FK_RESULT_TOOL
        FOREIGN KEY (TOOL_ID)
        REFERENCES SUPPORT_TOOL (TOOL_ID),

    CONSTRAINT CHK_RESULT_TYPE
        CHECK (
            RESULT_TYPE IN ('audio', 'text', 'exercise')
        )
);
