name: Print Software Versions

on:
  push:
    branches: 
      - main
      - LW11

jobs:

  PrintLanguageVersions:
    runs-on: ubuntu-22.04

    steps:
      - name: Print Node.js Version
        run: node --version

      - name: Print NPM Version
        run: npm --version

      - name: Print Python Version
        run: python --version

  PrintDBMSVersions:
    runs-on: ubuntu-22.04
    needs: [PrintLanguageVersions]

    steps:
      - name: Print PostgreSQL Version
        run: psql --version

      - name: Install MongoDB
        run: |
          wget -qO - https://pgp.mongodb.com/server-7.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org

      - name: Print MongoDB Version
        run: mongod --version
