name: Print Software Versions

on:
  push:
    branches: 
      - main
      - LW11

jobs:

  PrintLanguageVersions:
    runs-on: ubuntu-latest

    steps:
      - name: Print Node.js Version
        run: node --version

      - name: Print NPM Version
        run: npm --version

      - name: Print Python Version
        run: python --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]

    steps:
      - name: Print PostgreSQL Version
        run: psql --version

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install MongoDB Shell
        run: |
          curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
          sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
      
          echo "deb [ arch=amd64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] \
          https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/7.0 multiverse" | \
          sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
      
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Print MongoDB Version
        run: mongosh --version
