name: Program Code Convention Check

on:
  push:
    branches: [ main, LW11 ]

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
